[project]
name = "sbeditor"
version = "0.0.1"
dependencies = ["requests", "colorama", "setuptools"]

[project.optional-dependencies]
dev = ["faretek1"]

[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
