ID_DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\"£$%^&*()-_+=[]{}:;'@#~,.?<>/\\|`¬¦"
ID_BASE = len(ID_DIGITS)

EXTENSIONS = {"boost": "LEGO BOOST Extension",
              "ev3": "LEGO MINDSTORMS EV3 Extension",
              "gdxfor": "Go Direct Force & Acceleration Extension",
              "makeymakey": "Makey Makey Extension",
              "microbit": "micro:bit Extension",
              "music": "Music Extension",
              "pen": "Pen Extension",
              "text2speech": "Text to Speech Extension",
              "translate": "Translate Extension",
              "videoSensing": "Video Sensing Extension",
              "wedo2": "LEGO Education WeDo 2.0 Extension",
              "coreExample": "CoreEx Extension"}

INPUT_CODES = {"null": 1,
               "block": 2,
               "number": 4,
               "positive number": 5,
               "positive integer": 6,
               "integer": 7,
               "angle": 8,
               "color": 9,
               "string": 10,
               "broadcast": 11,
               "variable": 12,
               "var": 12,
               "list": 13}


STACK_TYPES = {
    "motion_movesteps": "stack",
    "motion_turnright": "stack",
    "motion_turnleft": "stack",
    "motion_goto": "stack",
    "motion_gotoxy": "stack",
    "motion_glideto": "stack",
    "motion_glidesecstoxy": "stack",
    "motion_pointindirection": "stack",
    "motion_pointtowards": "stack",
    "motion_changexby": "stack",
    "motion_setx": "stack",
    "motion_changeyby": "stack",
    "motion_sety": "stack",
    "motion_ifonedgebounce": "stack",
    "motion_setrotationstyle": "stack",
    "motion_xposition": "reporter",
    "motion_yposition": "reporter",
    "motion_direction": "reporter",
    "motion_scroll_right": "stack",
    "motion_scroll_up": "stack",
    "motion_align_scene": "stack",
    "motion_xscroll": "reporter",
    "motion_yscroll": "reporter",
    "motion_goto_menu": "reporter (menu)",
    "motion_glideto_menu": "reporter (menu)",
    "motion_pointtowards_menu": "reporter (menu)",

    "looks_sayforsecs": "stack",
    "looks_say": "stack",
    "looks_thinkforsecs": "stack",
    "looks_think": "stack",
    "looks_switchcostumeto": "stack",
    "looks_nextcostume": "stack",
    "looks_switchbackdropto": "stack",
    "looks_switchbackdroptoandwait": "stack",
    "looks_nextbackdrop": "stack",
    "looks_changesizeby": "stack",
    "looks_setsizeto": "stack",
    "looks_changeeffectby": "stack",
    "looks_seteffectto": "stack",
    "looks_cleargraphiceffects": "stack",
    "looks_show": "stack",
    "looks_hide": "stack",
    "looks_gotofrontback": "stack",
    "looks_goforwardbackwardlayers": "stack",
    "looks_costumenumbername": "reporter",
    "looks_backdropnumbername": "reporter",
    "looks_size": "reporter",
    "looks_hideallsprites": "stack",
    "looks_setstretchto": "stack",
    "looks_changestretchby": "stack",
    "looks_costume": "reporter (menu)",
    "looks_backdrops": "reporter (menu)",

    "sound_playuntildone": "stack",
    "sound_play": "stack",
    "sound_stopallsounds": "stack",
    "sound_changeeffectby": "stack",
    "sound_seteffectto": "stack",
    "sound_cleareffects": "stack",
    "sound_changevolumeby": "stack",
    "sound_setvolumeto": "stack",
    "sound_volume": "reporter",
    "sound_sounds_menu": "reporter (menu)",

    "event_whenflagclicked": "hat",
    "event_whenkeypressed": "hat",
    "event_whenthisspriteclicked": "hat",
    "event_whenstageclicked": "hat",
    "event_whenbackdropswitchesto": "hat",
    "event_whengreaterthan": "hat",
    "event_whenbroadcastreceived": "hat",
    "event_broadcast": "stack",
    "event_broadcastandwait": "stack",
    "event_whentouchingobject": "hat",
    "event_broadcast_menu": "reporter (menu)",
    "event_touchingobjectmenu": "reporter (menu)",

    "control_wait": "stack",
    "control_forever": "stack (c-mouth)",
    "control_if": "stack (c-mouth)",
    "control_if_else": "stack (c-mouth)",
    "control_wait_until": "stack",
    "control_repeat_until": "stack (c-mouth)",
    "control_stop": "stack",
    "control_start_as_clone": "hat",
    "control_create_clone_of": "stack",
    "control_delete_this_clone": "stack",
    "control_for_each": "stack (c-mouth)",
    "control_while": "stack (c-mouth)",
    "control_get_counter": "reporter",
    "control_incr_counter": "stack",
    "control_clear_counter": "stack",
    "control_all_at_once": "stack (c-mouth)",
    "control_create_clone_of_menu": "reporter (menu)",

    "sensing_touchingobject": "reporter (boolean)",
    "sensing_touchingcolor": "reporter (boolean)",
    "sensing_coloristouchingcolor": "reporter (boolean)",
    "sensing_distanceto": "reporter",
    "sensing_askandwait": "stack",
    "sensing_answer": "reporter",
    "sensing_keypressed": "reporter (boolean)",
    "sensing_mousedown": "reporter (boolean)",
    "sensing_mousex": "reporter",
    "sensing_mousey": "reporter",
    "sensing_setdragmode": "stack",
    "sensing_loudness": "reporter",
    "sensing_timer": "reporter",
    "sensing_resettimer": "stack",
    "sensing_of": "reporter",
    "sensing_current": "reporter",
    "sensing_dayssince2000": "reporter",
    "sensing_username": "reporter",
    "sensing_loud": "reporter (boolean)",
    "sensing_userid": "reporter",
    "sensing_touchingobjectmenu": "reporter (menu)",
    "sensing_distancetomenu": "reporter (menu)",
    "sensing_keyoptions": "reporter (menu)",
    "sensing_of_object_menu": "reporter (menu)",

    "operator_add": "reporter",
    "operator_subtract": "reporter",
    "operator_multiply": "reporter",
    "operator_divide": "reporter",
    "operator_random": "reporter",
    "operator_gt": "reporter (boolean)",
    "operator_lt": "reporter (boolean)",
    "operator_equals": "reporter (boolean)",
    "operator_and": "reporter (boolean)",
    "operator_or": "reporter (boolean)",
    "operator_not": "reporter (boolean)",
    "operator_join": "reporter",
    "operator_letter_of": "reporter",
    "operator_length": "reporter",
    "operator_contains": "reporter (boolean)",
    "operator_mod": "reporter",
    "operator_round": "reporter",
    "operator_mathop": "reporter",

    "data_variable": "reporter",
    "data_setvariableto": "stack",
    "data_changevariableby": "stack",
    "data_showvariable": "stack",
    "data_hidevariable": "stack",
    "data_listcontents": "reporter",
    "data_addtolist": "stack",
    "data_deleteoflist": "stack",
    "data_deletealloflist": "stack",
    "data_insertatlist": "stack",
    "data_replaceitemoflist": "stack",
    "data_itemoflist": "reporter (boolean)",
    "data_itemnumoflist": "reporter",
    "data_lengthoflist": "reporter",
    "data_listcontainsitem": "reporter (boolean)",
    "data_showlist": "stack",
    "data_hidelist": "stack",
    "data_listindexall": "reporter (menu)",
    "data_listindexrandom": "reporter (menu)",

    "procedures_definition": "hat",
    "procedures_call": "stack",
    "procedures_declaration": "stack",
    "procedures_prototype": "stack",

    "argument_reporter_string_number": "reporter",
    "argument_reporter_boolean": "reporter (boolean)",
    "argument_editor_reporter": "reporter (boolean)",
    "argument_editor_string_number": "reporter",

    "music_playDrumForBeats": "stack",
    "music_restForBeats": "stack",
    "music_playNoteForBeats": "stack",
    "music_setInstrument": "stack",
    "music_setTempo": "stack",
    "music_changeTempo": "stack",
    "music_getTempo": "reporter",
    "music_midiPlayDrumForBeats": "stack",
    "music_midiSetInstrument": "stack",
    "music_menu_DRUM": "reporter (menu)",
    "music_menu_INSTRUMENT": "reporter (menu)",

    "pen_clear": "stack",
    "pen_stamp": "stack",
    "pen_penDown": "stack",
    "pen_penUp": "stack",
    "pen_setPenColorToColor": "stack",
    "pen_changePenColorParamBy": "stack",
    "pen_setPenColorParamTo": "stack",
    "pen_changePenSizeBy": "stack",
    "pen_setPenSizeTo": "stack",
    "pen_setPenHueToNumber": "stack",
    "pen_changePenHueBy": "stack",
    "pen_setPenShadeToNumber": "stack",
    "pen_changePenShadeBy": "stack",
    "pen_menu_colorParam": "reporter (menu)",

    "videoSensing_whenMotionGreaterThan": "hat",
    "videoSensing_videoOn": "reporter",
    "videoSensing_videoToggle": "stack",
    "videoSensing_setVideoTransparency": "stack",
    "videoSensing_menu_ATTRIBUTE": "reporter (menu)",
    "videoSensing_menu_SUBJECT": "reporter (menu)",
    "videoSensing_menu_VIDEO_STATE": "reporter (menu)",

    "text2speech_speakAndWait": "stack",
    "text2speech_setVoice": "stack",
    "text2speech_setLanguage": "stack",
    "text2speech_menu_voices": "reporter (menu)",
    "text2speech_menu_languages": "reporter (menu)",

    "translate_getTranslate": "reporter",
    "translate_getViewerLanguage": "reporter",
    "translate_menu_languages": "reporter (menu)",

    "makeymakey_whenMakeyKeyPressed": "hat",
    "makeymakey_whenCodePressed": "hat",
    "makeymakey_menu_KEY": "reporter (menu)",
    "makeymakey_menu_SEQUENCE": "reporter (menu)",

    "microbit_whenButtonPressed": "",
    "microbit_isButtonPressed": "",
    "microbit_whenGesture": "",
    "microbit_displaySymbol": "",
    "microbit_displayText": "",
    "microbit_displayClear": "",
    "microbit_whenTilted": "",
    "microbit_isTilted": "",
    "microbit_getTiltAngle": "",
    "microbit_whenPinConnected": "",
    "microbit_menu_buttons": "",
    "microbit_menu_gestures": "",
    "microbit_menu_tiltDirectionAny": "",
    "microbit_menu_tiltDirection": "",
    "microbit_menu_touchPins": "",
    "microbit_menu_pinState": "",

    "ev3_motorTurnClockwise": "",
    "ev3_motorTurnCounterClockwise": "",
    "ev3_motorSetPower": "",
    "ev3_getMotorPosition": "",
    "ev3_whenButtonPressed": "",
    "ev3_whenDistanceLessThan": "",
    "ev3_whenBrightnessLessThan": "",
    "ev3_buttonPressed": "",
    "ev3_getDistance": "",
    "ev3_getBrightness": "",
    "ev3_beep": "",
    "ev3_menu_motorPorts": "",
    "ev3_menu_sensorPorts": "",

    "boost_motorOnFor": "",
    "boost_motorOnForRotation": "",
    "boost_motorOn": "",
    "boost_motorOff": "",
    "boost_setMotorPower": "",
    "boost_setMotorDirection": "",
    "boost_getMotorPosition": "",
    "boost_whenColor": "",
    "boost_seeingColor": "",
    "boost_whenTilted": "",
    "boost_getTiltAngle": "",
    "boost_setLightHue": "",
    "boost_menu_MOTOR_ID": "",
    "boost_menu_MOTOR_DIRECTION": "",
    "boost_menu_MOTOR_REPORTER_ID": "",
    "boost_menu_COLOR": "",
    "boost_menu_TILT_DIRECTION_ANY": "",
    "boost_menu_TILT_DIRECTION": "",

    "wedo2_motorOnFor": "",
    "wedo2_motorOn": "",
    "wedo2_motorOff": "",
    "wedo2_startMotorPower": "",
    "wedo2_setMotorDirection": "",
    "wedo2_setLightHue": "",
    "wedo2_whenDistance": "",
    "wedo2_whenTilted": "",
    "wedo2_getDistance": "",
    "wedo2_isTilted": "",
    "wedo2_getTiltAngle": "",
    "wedo2_playNoteFor": "",
    "wedo2_menu_MOTOR_ID": "",
    "wedo2_menu_MOTOR_DIRECTION": "",
    "wedo2_menu_OP": "",
    "wedo2_menu_TILT_DIRECTION_ANY": "",
    "wedo2_menu_TILT_DIRECTION": "",

    "gdxfor_whenGesture": "",
    "gdxfor_whenForcePushedOrPulled": "",
    "gdxfor_getForce": "",
    "gdxfor_whenTilted": "",
    "gdxfor_isTilted": "",
    "gdxfor_getTilt": "",
    "gdxfor_isFreeFalling": "",
    "gdxfor_getSpinSpeed": "",
    "gdxfor_getAcceleration": "",
    "gdxfor_menu_gestureOptions": "",
    "gdxfor_menu_pushPullOptions": "",
    "gdxfor_menu_tiltAnyOptions": "",
    "gdxfor_menu_tiltOptions": "",
    "gdxfor_menu_axisOptions": "",

    "coreExample_exampleOpcode": "reporter",
    "coreExample_exampleWithInlineImage": "stack",

    "note": "reporter (menu)",
    "matrix": "reporter (menu)",
    "red_hat_block": "hat"
}